paths:
  .github/workflows/**/*.{yml,yaml}:
    ignore:
      - 'property "workflow_(repository|sha)" is not defined in object type'
      - 'specifying action "\$/[^"]+" in invalid format because ref is missing'
      - 'reusable workflow call "\$/[^"]+" at "uses" is not following the format'
