name: CI

on:
  pull_request:
  push:
    branches: [main, develop]
    tags: ["v*.*.*"]

permissions: {}

jobs:
  check:
    uses: Metrify-App/metrify-workflows/.github/workflows/check.yml@v1
    permissions:
      contents: read
    with:
      node-version: "24"
      cache-paths: ~/.npm
      cache-key-files: package-lock.json
    secrets:
      make-env: ${{ secrets.TEST_ENV }}

  docker:
    needs: check
    uses: Metrify-App/metrify-workflows/.github/workflows/docker.yml@v1
    permissions:
      contents: read
      packages: write
