name: CI

on:
  pull_request:
  push:
    branches: [main, develop]
    tags: ["v*.*.*"]

permissions: {}

jobs:
  lint:
    uses: Metrify-App/metrify-workflows/.github/workflows/lint.yml@v1
    permissions:
      contents: read

  test:
    uses: Metrify-App/metrify-workflows/.github/workflows/test.yml@v1
    permissions:
      contents: read
    secrets:
      make-env: ${{ secrets.TEST_ENV }}

  docker:
    needs: [lint, test]
    uses: Metrify-App/metrify-workflows/.github/workflows/docker.yml@v1
    permissions:
      contents: read
      packages: write
